### PR TITLE
Map branch: Added Emeralds (gems) and Shrimp (crab) bonus varieties

### PR DESCRIPTION
**Pull request by MeuhV1**

### CODE REVIEW

**Comment by dguenms** [comment]
Can you also add the clam waves under the shrimp models like you did for murex? Right now they look like they're hovering above the water.

**Comment by MeuhV1** [comment]
I'm not sure if I can do that. I can add the waves to the model, but I don't know if I can merge the animations to the animation file of the shrimps. But I will give it a shot.

**Comment by dguenms** [comment]
Oh, that's what makes it more challenging. But I think even unanimated waves would look better.

**Comment by MeuhV1** [comment]
Added static waves

**Comment by MeuhV1** [comment]
This PR is ready to be merged BTW. (already since last update ;))

**Comment by dguenms** [comment]
I know, I want to look at it again inside the game. Will get to it on the next iteration of the map.

**Pull request merged**
