### PR TITLE
New tech and civic buttons

### PR DESCRIPTION
**Pull request by temujin2k**
Hi, Leo!

I'm creating this pull request for purely aesthetic reasons only. While I really love the new tech tree, I don't like many of the buttons that came with it, so I changed a bunch of them. They were either reverted to the vanilla versions of equivalent techs; or replaced them with buttons either from vanilla, HR, RI, or those I made myself. I haven't taken screenshots of the unchanged versions, but here is how the [tech tree](http://drive.google.com/uc?export=view&id=0BxZ8aO6P2GIINW5rOHVSaGNTRjQ) and the [civics screen](http://drive.google.com/uc?export=view&id=0BxZ8aO6P2GIIdnJIMUFPb1RLYVk) should look like (the tech tree is not updated to the latest commit, though).

I hope many of the proposed buttons (if not all) could be included in the upcoming release of v1.15. I am very much open to any comments, suggestion, and feedback you have. Thank you very much! :)

~ CFC Forums: @h0spitall3rz

[EDIT] PS: I've actually had this for a long time now, ever since you made the hrtechs branch. I just decided to make the pull request now since v1.15 is about to be released.

### CODE REVIEW

**Comment by dguenms** [comment]
Thanks for the suggestions. I spent a lot of time on selecting the current buttons, so don't be surprised if I want to keep most of them. However, you found many improvements in cases where I wasn't happy with my own buttons. Here's my first list of buttons where I definitely prefer yours:

Techs:
* Medicine
* Patronage
* Companies
* Flight
* Psychology
* Social Services
* Globalism
* Superconductors

Civics:
* Colonialism

Also, I would like the your Scholarship button for Writing, and the current Writing button for Edubba. Likewise, your Meritocracy button would make a good Civil Service button in my opinion.

There are a couple of additonal tech buttons where I am currently undecided. I think I need to compare each of them side by side and will get back to you later.

**Comment by dguenms** [comment]
Two others I would like added:
* Nanotechnology
* Journalism

If you can make a pull request containing only the buttons I mentioned, I would merge that. Maybe you can still offer this branch as a modmod though.

**Comment by temujin2k** [comment]
Yay! Thank you very much, Leo! Your suggestions have been noted, though I'm still not sure whether to wait for more suggestions. I apologize for having to change a lot of the buttons, I only did this because I felt the need to improve on many of the buttons to make it retain as much as possible the "Civ 4 buttons feel" even though they are new techs. To be fair, most of the buttons I replaced are actually from HR which just got ported into DoC--many of the buttons you chose are actually good! I guess I'll just defend my choice of buttons here--those that I strongly feel should be replaced. :)

TECHS [TL;DR] (techs marked with an * have their original buttons from HR)

- [ ] **Academia*** - I just improved on the original HR Humanities button: it looked too dull for me so I got another picture, zoomed it in, and made it more vivid.
- [ ] **Aesthetics*** - I don't know where HR got the image for the button, but I could not find something similar to that.
- [ ] **Artificial Intelligence*** - The button isn't clear enough.
- [ ] **Artisanry*** - I preferred the chinaware button because for me it gave more of the "Civ 4 feel" where the tech is represented by something related to it (such as a product) if the concept is too abstract.
- [ ] **Automation*** - Too cartoony or modern, for me it did not fit the Civ 4 theme well. (But I also feel the need to replace this again: see Sociology.)
- [ ] **Aviation*** - We could use the vanilla Flight button for this instead.
- [ ] **Ballistics*** - Looked too much of a real image for me, so I put the vanilla Artillery button here.
- [ ] **Biology*** - Having second thoughts on this, though, the original plant button can be used instead of the microscope one I found from RI.
- [ ] **Biotechnology*** - Same as Automation; the button is from another bundled Civ 4 mod.
- [ ] **Cartography*** - I found a better-looking button from SoI.
- [ ] **Composites*** - Looked weird, but I myself too don't think the vanilla one fits either. Will try to make a new one.
- [ ] **Cement** - Looked dull for me, but maybe that would do too! I just wanted to represent it through bricks.
- [ ] **Contract*** - Original button from HR. My eyes can't distinguish the details well. The one I got from RI looks nicer.
- [ ] **Doctrine*** - This is the HR Evangelism button, but it's actually from Europa Universalis III. Personally I don't think the EU3 idea buttons fit well in Civ 4. I strongly think vanilla Priesthood button is better here.
- [ ] **Economics** - Though I agree that the button is nice, it looks more like it should be assigned to an Industrial or later tech, considering that this is a Renaissance one (see the tuxedo sleeves). However, if a compromise is desired, I can just edit the button to look more vivid.
- [ ] **Exploration*** - Original HR Charter button, also from EU3. I found a (seemingly) much more appropriate button from SoI.
- [ ] **Fission*** - Looks a bit too real too, I prefer the vanilla one.
- [ ] **Fortification** - I proposed something with a brighter lighting. The current one looks sad for me.
- [ ] **Geography** - I found the globe button better for me, but the button you made is nice too! I'm totally fine if you want to keep the button. :)
- [ ] **Heritage*** - I found a better-looking art-related button from RFCE, though instead of using that directly I replicated it using a different image and improved its aesthetic.
- [ ] **Judiciary*** - Was not convinced enough with the original HR Jurisprudence button, good thing I found one from RI.
- [ ] **Law*** - I'd prefer using the vanilla Code of Laws one, though this one is nice too, and can be kept.
- [ ] **Leverage***, **Masonry*** - The vanilla Wheel and Masonry buttons look better for me.
- [ ] **Machine Tools** - The intricate details of the machine in the button made it look a bit messy, I prefer the original one from HR. Alternatively, the Textile Mill button from RFCE is a good alternative too?
- [ ] **Metallurgy*** - Methinks the vanilla Steel button is better.
- [ ] **Mythology** - If I'm not mistaken, the button depicts a Catholic mass. Or maybe something else. But I'm pretty sure it does not look mythical. I want to use the vanilla Mysticism button although I'm not sure if it's accurate either.
- [ ] **Navigation*** - From HR too, and from EU3 too. Could be represented by the Astrolabe button from other RFC modmods instead. (Or maybe the vanilla Astronomy one? Idk.)
- [ ] **Nationalism** - This is the Occupation button from the old , right? Since the Nationhood button is already used and I don't think the vanilla Nationalism button is accurate, I chose the vanilla Military Tradition instead.
- [ ] **Pastoralism*** - Too cluttered. The vanilla one already works for me.
- [ ] **Politics*** - The button is very unclear. I chose the chess pieces button (from SoI) as it can be a metaphor of politics too.
- [ ] **Representation*** - The vanilla Democracy button looks better for it, but the current one (from HR) would do too if desired.
- [ ] **Robotics*** - Button looks very blurry too. I'd prefer restoring the vanilla Robotics tech instead.
- [ ] **Sailing*** - Did not pass my tech button standards, so I replaced it with the vanilla one.
- [ ] **Shipbuilding*** - It does not look enough like part of the ship w/o a caption. Found another button from RFCE.
- [ ] **Social Contract** - I go for let's revert the vanilla Constitution civic and tech buttons to their original ones.
- [ ] **Sociology** - The Philosophy button already uses The Thinking Man, so to avoid redundancy I chose the vanilla Liberalism tech. (Speaking of redundancy, this also means the Automation button should be replaced, but Idk yet what to represent the tech with.)
- [ ] **Statecraft*** - Also from EU3. I think the vanilla Monarchy tech is better--statecraft is the the skillful management of state affairs, anyway.

CIVICS:

- [ ] **Republic** - A painting-like one for me should be ideally preferred over a cartoony one.
- [ ] **Constitution** - Same stuff as Social Contract tech.
- [ ] **Monarchy** - The vanilla Hereditary Rule tech looks better (for me)!
- [ ] **Meritocracy** - (see PS)
- [ ] **Manorialism** - Does not look high quality to me. The one RFCE uses looks better for me.
- [ ] **State Party** - The proposed button looks more communist to me. (Sorry for the stereotype, brothers!)
- [ ] (For the rest of the civic button changes not mentioned, keeping the current ones is a good idea too.)

PS: 
- **Steel**, **Individualism** - I just fixed the buttons.
- **Civil Service** - Actually, originally I put the Meritocracy button on Civil Service just as you mentioned. But then I noticed the Meritocracy button was messy, hence, the proposed. However, we can either switch the two proposed buttons instead, or keep the current Meritocracy button. :)
- **Writing** - I'll try to improve on the button I made.
- **Scholarship** - I want to replace the current button but I also don't know what to replace it with.

**Comment by dguenms** [comment]
It seems we have different goals here. I deliberately tried to move away from the default Civ4 feel (or continue to use HR buttons where they moved away from Civ4 buttons) to indicate that this is an entirely new tech tree. I also usually find the replacements to the default Civ4 buttons more aesthetically pleasing, but that is of course personal preference.

Also, in general I prefer "pixel art" like buttons that are more abstract, and try to avoid high res buttons that are translated from paintings etc.

Your reasoning makes sense to me in most cases, but considering that my goals are different my decisions remain unchanged. So you don't have to wait for further input from me.

**Comment by temujin2k** [comment]
Ah, okay! Point taken. Will push in a few hours. Thank you! :)

**Comment by dguenms** [comment]
Thank you for this pull request. This help is greatly appreciated. Looking forward to your changes.

**Comment by temujin2k** [comment]
Thank you also for your input! I did not know that those changes were intentional. I was only concerned with aesthetics--of course the tech tree was new so it didn't mind to me anymore where the buttons come from.

**Comment by dguenms** [comment]
Hey, can you give me a quick update on the state of this PR? I'd like to know if I can plan for its inclusion before the 1.15 release.

**Comment by dguenms** [comment]
Another comment, I just realised that your proposed Journalism button might already be in use by the News Press. Please double check before including that button.

**Comment by temujin2k** [comment]
Hello, I apologize for the delay due to the big load of schoolwork. I'll try my best to finalize everything in three days. Anyway, I made a new Journalism button. I just checked the art assets and I confirm that the one I made is not similar to the News Press button.

**Comment by bnxkpc** [comment]
Hi, Leo! I think I messed up this branch when I updated it days ago. I'll close this one and make a new one. I apologize for the hassle.

**Comment by temujin2k** [comment]
Never mind the one I said I'll delete this branch; I already fixed it. Here it is. By the way, I made a different one for Writing. I hope it's better than the one I made previously.

**Comment by dguenms** [comment]
Alright, thanks! I'll look at it in the game again.

**Comment by dguenms** [comment]
Okay, looks great! Unfortunately you also need to revert the Civil Service button, however. I realised it is already used by the Taixue building.

**Comment by temujin2k** [comment]
Hmmm. How about I revert the Writing and Edubba buttons, and replace the Taixue button with the Writing button I made? The Edubba button is already good for me, actually. (Lowkey really wanting to use that button for Civil Service...)

**Comment by dguenms** [comment]
I think I prefer simply reverting.

**Comment by dguenms** [comment]
Any updates?

**Comment by dguenms** [comment]
*ping*

**Comment by temujin2k** [comment]
Sorry I wasn't able to focus on this anymore. Will look again

**Comment by temujin2k** [comment]
Hello, Leo, sorry it took me a long time to do this--I had to clone again, actually since my local copies are a mess. Still open for other requests if any. :)

PS: Would it be okay if I post all of the buttons as a modmod I compiled on the forums?

**Comment by dguenms** [comment]
Great, I'll give it another review.

And of course you can create a modmod with the additional buttons.

**Pull request merged**
