### PR TITLE
New buttons

### PR DESCRIPTION
**Pull request by SgtBears**
Added the Catholic Icon to the Apostolic Palace.
Added Unique buttons to the Zoroastrian Cathedral, Monastery and Temple.
Added New and more accurate button for Sejong.
Added Orthodox icon to the Orthodox Shrine.
Added Protestant Icon to the Protestant Shrine.
Added Grass Background and Border to Statesman unit and Female Statesman unit.
Added Background and Border to Textile Industry, Fishing Industry, Oil Industry, Silk Road, Cereal Industry, Bhutto Leader, Cleopatra Leader and Nicholas II Leader.
Added Border to Phoenician Glassmaker, Corvette, Porcelain Tower, Francis I, Gerhardsen, getulio, San Martin, Khomeni, Macdonald, Maria II, Peron, George I, William III, Castilla and Rajendra.

### CODE REVIEW

**Comment by dguenms** [comment]
Will give it a look from inside the game before merging.

**Comment by dguenms** [comment]
Have you seen my reply to the Zoroastrian/Sejong buttons?

**Comment by SgtBears** [comment]
Yeah, I'm just finishing the Various Delectat First. I'll import the art from Histroy Rewritten.

**Comment by dguenms** [comment]
Okay great!

**Comment by dguenms** [comment]
Could you change the backslashes in the XML to forward slashes?

**Comment by SgtBears** [comment]
Updated and fixed the backslashes

**Pull request merged**
