### PR TITLE
Various Text Updates

### PR DESCRIPTION
**Pull request by SgtBears**
Various Text Updates.

Which TXT_KEY_STABILITY_NEIGHBORS do you want.
----- Collapsing Neighbors
----- Neighbors

### CODE REVIEW

**Comment by dguenms** [comment]
No, it's a good idea to have proper leaders for the Independents and Natives. I prefer Collapsing Neighbors for the stability tooltip.

**Comment by SgtBears** [comment]
Removed Leaders, chose collapsing neighbors.
This Pull request should fix all the TXT_KEYs people have been experiencing.

**Comment by dguenms** [comment]
Oh sorry, only now did I realize that my previous comment was ambiguous. I meant to say that it was a good idea to give them their own ("proper" in that sense) leaders. If you still want to, you can re-include them.

**Comment by SgtBears** [comment]
Facepalm...   :) Added Leaders again. Added a DerivativeCivilization to all civilizations.

**Comment by dguenms** [comment]
Great, thanks.

**Pull request merged**
