### PR TITLE
Building Order

### PR DESCRIPTION
**Pull request by SgtBears**
I have checked the order of the BuildingInfos, Constants and Dll constants 3 times and fixed the bug you mentioned. There is no xml or python errors when loading but I haven't check the contants or dll constants in game (I don't know how).

### CODE REVIEW

**Comment by dguenms** [comment]
Thanks. I will compile the source tomorrow and check if the constants are correct. By the way, there's no need to make a new pull request to change your files. Simply push your changes to the same branch (in this case develop) the PR originated from.

**Comment by SgtBears** [comment]
I have ordered the unmodified Promotions, Resources and Units and have added them to the Merge request.
My Modified text files are ready for merge once the unmoddified text files have been added.

**Comment by dguenms** [comment]
Haven't gotten around to look at these changes in detail since I'm currently working on my own branch. Will return later to test them and then merge the PR.

**Comment by dguenms** [comment]
Okay double checked everything, and found nothing. Ready to merge.

**Pull request merged**
