### PR TITLE
Python cleanup

### PR DESCRIPTION
**Pull request by MeuhV1**
Aligned tabs in python files (replaced 8 spaces with a tab) This gives a better display of the code in Notepad++

Included new civic screen with combo info

### CODE REVIEW

**Comment by dguenms** [comment]
That was long overdue, thanks for taking care of that. Will merge soon.

**Comment by dguenms** [comment]
Sorry, another merge caused a conflict. Hard to avoid when almost all files are affected :/

**Comment by MeuhV1** [comment]
That's true. But I updated my branch so the conflicts are gone.

**Comment by MeuhV1** [comment]
I've also included some changes in the civic screen to show good/bad combos
(I think it's unnecessary to create another branch for this)

**Comment by dguenms** [comment]
Okay, but I will have to look at it in game.

Thanks for making the branch compatible again.

**Comment by dguenms** [comment]
Okay, looks good. The code mght need to be refactored again later so that Stability.py and the display rely on the same definitions but that's not required right away.

**Pull request merged**
