### PR TITLE
Platybuilder

### PR DESCRIPTION
**Pull request by MeuhV1**
Fixed a small bug in the PlayerData screen
Added a feature to enable/disable secondary civs via the WB (PlayerData screen)

Sorry about the messy changelog, I just can't make it clean. I just don't understand Git well enough yet.

### CODE REVIEW

**Comment by dguenms** [comment]
Can you make the commit history a question in either the Git or modmodding thread? That is, what exactly did you do? It makes it hard to manually squash the history every time, and it should only be a rebase for you.

**Comment by MeuhV1** [comment]
I thought I rebased it, but it seems something went wrong there.

What do you exaclty mean with commit history?

**Comment by dguenms** [comment]
Oh, I just meant the general topic. If the rebase went through, maybe you need to revert your commits first. I think it's easier to discuss that on the forum.

**Comment by dguenms** [comment]
Okay, this apparently easier than I thought with TortoiseGit. Look at TortoiseGit -> Show log. The list there should show all commits including the repeating/test/fix commits we want to get rid of. You can select multiple commits with the Ctrl key. Afterwards right clicking should give you the option to combine the selected commits.

Clean up your develop branch this way. Not sure if rebasing from develop will fix this branch then, otherwise you have to do the same again here.

**Comment by MeuhV1** [comment]
I don't see an option combine commits or something similar when I right click after selecting multiple commits.

**Comment by dguenms** [comment]
Not even when selecting them pairwise?

**Comment by dguenms** [comment]
Squashed commits and merged.

**Pull request closed without merging**
