### PR TITLE
Platybuilder

### PR DESCRIPTION
**Pull request by MeuhV1**
Merged Platybuilder v4.17

### CODE REVIEW

**Comment by dguenms** [comment]
Is this the Platybuilder, or the WB from History Rewritten?

Also, the commit log looks really messy. Can you take a look [here](http://forums.civfanatics.com/showthread.php?p=14072675#post14072675) and rebase your fork and then start a pull request from a new branch?

**Comment by MeuhV1** [comment]
It's platybuilder, but that's the one HR uses. (Although I used a more recent version of platybuilder)

I will try to reorganize my fork. I did create a seperate branch for this feature however.

**Comment by dguenms** [comment]
Oh, I also thought that was the case. But then I looked into Platybuilder and it seemed very different than what HR has? Am I confusing something here?

And yeah, the branch is alright, but it since it includes your develop branch it seems to have inherited its cluttered history. If you rebase to DoC's develop things should look better.

**Comment by dguenms** [comment]
Okay, I checked again and the WB is indeed the same. I think I confused it with Platypedia?

Anyway, this looks good. I manually merged it to squash all the commits.

**Pull request closed without merging**
